#!/bin/bash
#PBS -l nodes=1:ppn=2
#PBS -l walltime=1:00:00
#PBS -l mem=2000MB
#PBS -N lpsolve_h2
#PBS -e /home/rcf-40/chen116/dynamo/lpsolve_matlab
#PBS -o /home/rcf-40/chen116/dynamo/lpsolve_matlab
cd /home/rcf-40/chen116/dynamo/lpsolve_matlab
if [ -e /usr/usc/matlab/default/setup.sh ]; then
	source /usr/usc/matlab/default/setup.sh
fi
if [ ! -d ./out ]; then
	mkdir "out"
fi

export LD_LIBRARY_PATH="/home/rcf-40/chen116/dynamo/lpsolve_matlab"
rm *.e*
rm *.o*
rm out/h2.txt
matlab -nosplash -nodesktop -r "run h2.m" >> ./out/h2.txt
