#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=24:00:00
#PBS -l mem=2000MB
#PBS -N g1
#PBS -e /home/rcf-40/chen116/dynamo/lpsolve_matlab
#PBS -o /home/rcf-40/chen116/dynamo/lpsolve_matlab
cd /home/rcf-40/chen116/dynamo/lpsolve_matlab
if [ -e /usr/usc/matlab/default/setup.sh ]; then
	source /usr/usc/matlab/default/setup.sh
fi
if [ ! -d ./out ]; then
	mkdir "out"
fi

export LD_LIBRARY_PATH="/home/rcf-40/chen116/dynamo/lpsolve_matlab"
rm *.e*
rm *.o*
matlab -nosplash -nodesktop -r "run g1.m" >> ./out/g1_node.txt
